services:
  api.database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    image: database:latest
    container_name: api.database
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "5432:5432"
    volumes:
      - api.database:/var/lib/postgresql

volumes:
  api.database: